package global.coda.hms.constant.applicationconstant.apiconstants;

public class PatientApiConstants {

    public static String ENTERED_PATIENTAPI_CREATE = "ENTERED_PATIENTAPI_CREATE";
    public static String PATIENT_CREATED_IN_PATIENTAPI = "PATIENT_CREATED_IN_PATIENTAPI";
    public static String SUCCESSFULLY_CREATED_PATIENT = "SUCCESSFULLY_CREATED_PATIENT";

    public static String ENTERED_PATIENTAPI_READ = "ENTERED_PATIENTAPI_READ";
    public static String PATIENT_READ_IN_PATIENTAPI = "PATIENT_READ_IN_PATIENTAPI";

    public static String ENTERED_PATIENTAPI_UPDATE="ENTERED_PATIENTAPI_UPDATE";
    public static String PATIENT_UPDATE_IN_PATIENTAPI="PATIENT_UPDATE_IN_PATIENTAPI";
    public static String SUCCESSFULLY_UPDATED_PATIENT="SUCCESSFULLY_UPDATED_PATIENT";

    public static String ENTERED_PATIENTAPI_DELETE="ENTERED_PATIENTAPI_DELETE";
    public static String PATIENT_DELETE_IN_PATIENTAPI="PATIENT_DELETE_IN_PATIENTAPI";
    public static String SUCCESSFULLY_DELETED_PATIENT="SUCCESSFULLY_DELETED_PATIENT";

}
