package global.coda.hms.constant.applicationconstant.delegateconstants;

public class PatientDelegateConstants {
    public static final String ENTERED_PATIENTDELEGATE_CREATE = "ENTERED_PATIENTDELEGATE_CREATE";
    public static final String PATIENT_CREATED_IN_PATIENTDELEGATE = "PATIENT_CREATED_IN_PATIENTDELEGATE";

    public static final String ENTERED_PATIENTDELEGATE_READ = "ENTERED_PATIENTDELEGATE_READ";
    public static final String PATIENT_READ_IN_PATIENTDELEGATE = "PATIENT_READ_IN_PATIENTDELEGATE";

    public static final String ENTERED_PATIENTDELEGATE_UPDATE = "ENTERED_PATIENTDELEGATE_UPDATE";
    public static final String PATIENT_UPDATE_IN_PATIENTDELEGATE = "PATIENT_UPDATE_IN_PATIENTDELEGATE";

    public static final String ENTERED_PATIENTDELEGATE_DELETE = "ENTERED_PATIENTDELEGATE_DELETE";
    public static final String PATIENT_DELETE_IN_PATIENTDELEGATE = "PATIENT_DELETE_IN_PATIENTDELEGATE";
}
